CREATE TABLE species (
  id INTEGER PRIMARY KEY NOT NULL,
  short TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  playable BIGINT NOT NULL
);

CREATE TABLE backgrounds (
  id INTEGER PRIMARY KEY NOT NULL,
  short TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  playable BIGINT NOT NULL
);

CREATE TABLE games (
  gid TEXT PRIMARY KEY NOT NULL,
  species_id INTEGER NOT NULL,
  background_id INTEGER NOT NULL,
  xl BIGINT NOT NULL,
  dam BIGINT NOT NULL,
  sdam BIGINT NOT NULL,
  tdam BIGINT NOT NULL,
  tmsg TEXT NOT NULL,
  turn BIGINT NOT NULL,
  dur BIGINT NOT NULL,
  runes BIGINT NOT NULL,
  score BIGINT NOT NULL,
  start DATETIME NOT NULL,
  end DATETIME NOT NULL,
  potions_used BIGINT NOT NULL,
  scrolls_used BIGINT NOT NULL,
  FOREIGN KEY(species_id) REFERENCES species(id),
  FOREIGN KEY(background_id) REFERENCES background(id)
);
