CREATE TABLE games (
  gid TEXT PRIMARY KEY NOT NULL,
  xl BIGINT NOT NULL,
  dam BIGINT NOT NULL,
  sdam BIGINT NOT NULL,
  tdam BIGINT NOT NULL,
  tmsg TEXT NOT NULL,
  turn BIGINT NOT NULL,
  dur BIGINT NOT NULL,
  runes BIGINT NOT NULL,
  score BIGINT NOT NULL,
  start DATETIME NOT NULL,
  end DATETIME NOT NULL,
  potions_used BIGINT NOT NULL,
  scrolls_used BIGINT NOT NULL
)
